/* eslint-disable react/react-in-jsx-scope */
// INFO: all svg icons will go below
import React from 'react';
import {Home} from './image/svgIcons/IcHome';
import {Phone} from './image/svgIcons/IcPhone';
import {BackArrow} from './image/svgIcons/IcBackArrow';
import {Delete} from './image/svgIcons/IcDelete';
import {ProfileIcon} from './image/svgIcons/IcProfileIcon';
import {Check} from './image/svgIcons/IcCheck';
import ClockIcon from './image/svgIcons/IcClock';
import {Youtube} from './image/svgIcons/IcYoutube';
import Close from './image/svgIcons/IcClose';
import Call from './image/svgIcons/IcCallIcon';
import CheckMark from './image/svgIcons/IcCheckMark';
import {Share} from './image/svgIcons/IcShare';
import {Search} from './image/svgIcons/IcSearch'
import {ForwardArrow} from './image/svgIcons/IcForwardArrow'
import {Google} from './image/svgIcons/IcGoogle'
import {Facebook, Sort} from './image/svgIcons/IcFacebook'
import {Heart} from './image/svgIcons/IcHeart'
import {Star} from './image/svgIcons/IcStar'
import { FilledHeart } from './image/svgIcons/IcFilledHeart';
import { Pen } from './image/svgIcons/IcPen';
import { HomeActive } from './image/svgIcons/IcHomeActive';
import { Shop } from './image/svgIcons/IcShop';
import { Cart } from './image/svgIcons/IcCart';
import { Favorite } from './image/svgIcons/IcFavorite';
import { Person } from './image/svgIcons/IcPerson';
import { HomeInactive } from './image/svgIcons/IcHomeInactive';
import { ShopActive } from './image/svgIcons/IcBagFilled';
import { CartActive } from './image/svgIcons/IcCartActive';
import { FavoriteActive } from './image/svgIcons/IcFavroiteActive';
import { PersonActive } from './image/svgIcons/IcPersonActive';
import { Filter } from './image/svgIcons/IcFilter';
import { SortIcon } from './image/svgIcons/IcSort';
import { Grid } from './image/svgIcons/IcGrid';
import { List } from './image/svgIcons/IcList';
import { CheckBoxInactive } from './image/svgIcons/IcCheckboxInactive';
import { CheckBoxActive } from './image/svgIcons/IcCheckboxActive';
import { Thumb } from './image/svgIcons/IcThumb';
import { Camera } from './image/svgIcons/IcCamera';
import { MasterCard } from './image/svgIcons/IcMasterCard';
import { Plus } from './image/svgIcons/IcPlus';
import { Help } from './image/svgIcons/IcHelp';
import { Minus } from './image/svgIcons/IcMinus';
import { ChevronRight } from './image/svgIcons/IcChevronRight';
import { ShowMore } from './image/svgIcons/IcShowMore';
import { FedEx } from './image/svgIcons/IcFedEx';
import { USPS } from './image/svgIcons/IcUSPS';
import { DHL } from './image/svgIcons/IcDHL';
import { EyeOpen } from './image/svgIcons/IcEyeOpen';

export const IcHome = props => <Home {...props} />;
export const IcPhone = props => <Phone {...props} />;
export const IcBackArrow = props => <BackArrow {...props} />;
export const IcDelete = props => <Delete {...props} />;
export const IcProfileIcon = props => <ProfileIcon {...props} />;
export const IcCheck = props => <Check {...props} />;
export const IcClock = props => <ClockIcon {...props} />;
export const IcYoutube = props => <Youtube {...props} />;
export const IcClose = props => <Close {...props} />;
export const IcCall = props => <Call {...props} />;
export const IcCheckMark = props => <CheckMark {...props} />;
export const IcShare = props => <Share {...props} />;
export const IcSearch = props => <Search {...props} />;
export const IcForwardArrow = props => <ForwardArrow {...props} />;
export const IcGoogle = props => <Google {...props} />;
export const IcFacebook = props => <Facebook {...props} />;
export const IcHeart = props => <Heart {...props} />;
export const IcStar = props => <Star {...props} />;
export const IcFilledHeart = props => <FilledHeart {...props} />;
export const IcPen = props => <Pen {...props} />;
export const IcHomeActive = props => <HomeActive {...props} />;
export const IcShop = props => <Shop {...props} />;
export const IcCart = props => <Cart {...props} />;
export const IcFavorite = props => <Favorite {...props} />;
export const IcPerson = props => <Person {...props} />;
export const IcHomeInactive = props => <HomeInactive {...props} />;
export const IcShopActive = props => <ShopActive {...props} />;
export const IcCartActive = props => <CartActive {...props} />;
export const IcFavoriteActive = props => <FavoriteActive {...props} />;
export const IcPersonActive = props => <PersonActive {...props} />;
export const IcFilter = props => <Filter {...props} />;
export const IcSortIcon = props => <SortIcon {...props} />;
export const IcGrid = props => <Grid {...props} />;
export const IcList = props => <List {...props} />;
export const IcCheckBoxInactive = props => <CheckBoxInactive {...props} />;
export const IcCheckBoxActive = props => <CheckBoxActive {...props} />;
export const IcThumb = props => <Thumb {...props} />;
export const IcCamera = props => <Camera {...props} />;
export const IcMasterCard = props => <MasterCard {...props} />;
export const IcPlus = props => <Plus {...props} />;
export const IcHelp = props => <Help {...props} />;
export const IcMinus = props => <Minus {...props} />;
export const IcChevronRight = props => <ChevronRight {...props} />;
export const IcShowMore = props => <ShowMore {...props} />;
export const IcFedEx = props => <FedEx {...props} />;
export const IcUSPS = props => <USPS {...props} />;
export const IcDHL = props => <DHL {...props} />;
export const IcEyeOpen = props => <EyeOpen {...props} />;