// INFO: all images will be exported from here
export const images = {
  imgAvatarLogo: require('./image/images/ImgAvatar.png'),
  imgMobileLogo: require('./image/images/ImgMobile.png'),
  imgDeleteLogo: require('./image/images/ImgDeleteLogo.png'),
  imgLogoutLogo: require('./image/images/ImgLogout.png'),
  imgNotification: require('./image/images/ImgNotification.png'),
  imgYoutube: require('./image/images/ImgYoutube.png'),
  imgAppNewLogo: require('./image/images/chandukaka.png'),
  imgAppLogoMain: require('./image/images/ImgAppLogoMain.png'),
  ImgCheck: require('./image/images/ImgCheck.png'),
  ImgCard: require('./image/images/ImageCard.png'),
  ImgBanner: require('./image/images/MainBanner.png'),
  imgOnBoardingImageBanner: require('./image/images/OnBoardingImageBanner.png'),
  imgOnBoardingImageBlack: require('./image/images/OnBoardingImageBlack.png'),
  imgOnBoardingImageMenHoodie: require('./image/images/OnBoardingImageMenHoodie.png'),
  imgNewCategory: require('./image/images/newCategoryImg.png'),
  imgClothesCategory: require('./image/images/clothesCategoryImg.png'),
  imgShoesCategory: require('./image/images/shoesCategoryImg.png'),
  imgAccessoriesCategory: require('./image/images/accessoriesCategoryImg.png'),
  imgMainProductImageOne: require('./image/images/MainProductImageOne.png'),
  imgMainProductImageTwo: require('./image/images/MainProductImageTwo.png'),
  imgAvatar: require('./image/images/Avatar.png'),
  imgReviewProductImgOne: require('./image/images/ReviewProductImgOne.png'),
  imgReviewProductImgTwo: require('./image/images/ReviewProductImgTwo.png'),
  imgReviewProductImgThree: require('./image/images/ReviewProductImgThree.png'),
  imgPaymentCardBG: require('./image/images/PaymentCardBG.png'),
  imgPaymentChip: require('./image/images/PaymentChip.png'),
  imgDiscount1: require('./image/images/DiscountImg1.png'),
  imgDiscount2: require('./image/images/DiscountImg2.png'),
  imgDiscount3: require('./image/images/DiscountImg3.png'),
  ImgOrderComplete: require('./image/images/ImgOrderComplete.png'),
  VisualSearchImage: require('./image/images/VisualSearchImage.png'),
};