// INFO: all images will be exported from here
export const images = {
  imgAvatarLogo: require('./image/images/ImgAvatar.jpg'),
  imgAppLogoMain: require('./image/images/ImgAppLogoMain.jpg'),
  ImgBanner: require('./image/images/MainBanner.jpg'),
  imgOnBoardingImageBanner: require('./image/images/OnBoardingImageBanner.jpg'),
  imgOnBoardingImageBlack: require('./image/images/OnBoardingImageBlack.jpg'),
  imgOnBoardingImageMenHoodie: require('./image/images/OnBoardingImageMenHoodie.jpg'),
  imgNewCategory: require('./image/images/newCategoryImg.jpg'),
  imgClothesCategory: require('./image/images/clothesCategoryImg.jpg'),
  imgShoesCategory: require('./image/images/shoesCategoryImg.jpg'),
  imgAccessoriesCategory: require('./image/images/accessoriesCategoryImg.jpg'),
  imgAvatar: require('./image/images/Avatar.jpg'),
  imgReviewProductImgOne: require('./image/images/ReviewProductImgOne.jpg'),
  imgReviewProductImgTwo: require('./image/images/ReviewProductImgTwo.jpg'),
  imgReviewProductImgThree: require('./image/images/ReviewProductImgThree.jpg'),
  imgPaymentCardBG: require('./image/images/PaymentCardBG.jpg'),
  imgPaymentChip: require('./image/images/PaymentChip.jpg'),
  imgDiscount1: require('./image/images/DiscountImg1.jpg'),
  imgDiscount2: require('./image/images/DiscountImg2.jpg'),
  imgDiscount3: require('./image/images/DiscountImg3.jpg'),
  ImgOrderComplete: require('./image/images/ImgOrderComplete.jpg'),
  VisualSearchImage: require('./image/images/VisualSearchImage.jpg'),
};

