// INFO: all images will be exported from here
export const images = {
  imgAvatarLogo: require('./image/images/ImgAvatar.jpg'),
  imgAppLogoMain: require('./image/images/ImgAppLogoMain.jpg'),
  ImgBanner: require('./image/images/MainBanner.jpg'),
  imgOnBoardingImageBanner: require('./image/images/OnBoardingImageBanner.jpg'),
  imgOnBoardingImageBlack: require('./image/images/OnBoardingImageBlack.jpg'),
  imgOnBoardingImageMenHoodie: require('./image/images/OnBoardingImageMenHoodie.jpg'),
  imgNewCategory: require('./image/images/newCategoryImg.jpg'),
  imgClothesCategory: require('./image/images/clothesCategoryImg.jpg'),
  imgShoesCategory: require('./image/images/shoesCategoryImg.jpg'),
  imgAccessoriesCategory: require('./image/images/accessoriesCategoryImg.jpg'),
  imgMainProductImageOne: require('./image/images/MainProductImageOne.jpg'),
  imgMainProductImageTwo: require('./image/images/MainProductImageTwo.jpg'),
  imgAvatar: require('./image/images/Avatar.jpg'),
  imgReviewProductImgOne: require('./image/images/ReviewProductImgOne.jpg'),
  imgReviewProductImgTwo: require('./image/images/ReviewProductImgTwo.jpg'),
  imgReviewProductImgThree: require('./image/images/ReviewProductImgThree.jpg'),
  imgPaymentCardBG: require('./image/images/PaymentCardBG.jpg'),
  imgPaymentChip: require('./image/images/PaymentChip.jpg'),
  imgDiscount1: require('./image/images/DiscountImg1.jpg'),
  imgDiscount2: require('./image/images/DiscountImg2.jpg'),
  imgDiscount3: require('./image/images/DiscountImg3.jpg'),
  ImgOrderComplete: require('./image/images/ImgOrderComplete.jpg'),
  VisualSearchImage: require('./image/images/VisualSearchImage.jpg'),
  productImage15: require('./image/images/productImage15.jpeg'),
  productImage14: require('./image/images/productImage14.jpeg'),
  productImage13: require('./image/images/productImage13.jpeg'),
  productImage12: require('./image/images/productImage12.jpeg'),
  productImage11: require('./image/images/productImage11.jpeg'),
  productImage10: require('./image/images/productImage10.jpeg'),
  productImage9: require('./image/images/productImage9.jpeg'),
  productImage8: require('./image/images/productImage8.jpeg'),
  productImage7: require('./image/images/productImage7.jpeg'),
  productImage6: require('./image/images/productImage6.jpeg'),
  productImage5: require('./image/images/productImage5.jpeg'),
  productImage4: require('./image/images/productImage4.jpeg'),
  productImage3: require('./image/images/productImage3.jpeg'),
  productImage2: require('./image/images/productImage2.jpeg'),
  EveningDress: require('./image/images/EveningDress.jpeg'),
};

