import { images } from "../../theme";

export const productList = [
  {
    "id": 1,
    "name": "Evening Dress",
    "brand": "H&M",
    "images": images.productImage1,
    "ratings": 2,
    "rating_count": 12,
    "originalPrice": 17.99,
    "discount": 10,
    "isProductOnSale": true,
    "saleProductPrice": 16.19,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "Black",
    "mainProductImageOne": "images.imgMainProductImageOne1",
    "mainProductImageTwo": "images.imgMainProductImageTwo1",
    "description": "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 2,
    "name": "Casual Shirt",
    "brand": "Zara",
    "images": images.productImage2,
    "ratings": 4,
    "rating_count": 8,
    "originalPrice": 25.99,
    "discount": 5,
    "isProductOnSale": false,
    "saleProductPrice": null,
    "isProductNew": false,
    "isProductSold": true,
    "productColor": "Blue",
    "mainProductImageOne": "images.imgMainProductImageOne2",
    "mainProductImageTwo": "images.imgMainProductImageTwo2",
    "description": "Casual shirt made of breathable cotton with a comfortable fit, perfect for everyday wear.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 3,
    "name": "Summer Dress",
    "brand": "Forever 21",
    "images": images.productImage3,
    "ratings": 5,
    "rating_count": 20,
    "originalPrice": 19.99,
    "discount": 15,
    "isProductOnSale": true,
    "saleProductPrice": 16.99,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "Yellow",
    "mainProductImageOne": "images.imgMainProductImageOne3",
    "mainProductImageTwo": "images.imgMainProductImageTwo3",
    "description": "Lightweight summer dress with floral print, perfect for sunny days. Features a v-neckline and adjustable straps.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 4,
    "name": "Denim Jacket",
    "brand": "Levi's",
    "images": images.productImage4,
    "ratings": 4,
    "rating_count": 15,
    "originalPrice": 49.99,
    "discount": 20,
    "isProductOnSale": false,
    "saleProductPrice": null,
    "isProductNew": false,
    "isProductSold": true,
    "productColor": "Denim Blue",
    "mainProductImageOne": "images.imgMainProductImageOne4",
    "mainProductImageTwo": "images.imgMainProductImageTwo4",
    "description": "Classic denim jacket with button-front closure and two chest pockets. Made from durable denim fabric.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 5,
    "name": "Leather Boots",
    "brand": "Dr. Martens",
    "images": images.productImage5,
    "ratings": 4,
    "rating_count": 10,
    "originalPrice": 99.99,
    "discount": 15,
    "isProductOnSale": true,
    "saleProductPrice": 84.99,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "Black",
    "mainProductImageOne": "images.imgMainProductImageOne5",
    "mainProductImageTwo": "images.imgMainProductImageTwo5",
    "description": "Sturdy leather boots with a lace-up front and iconic yellow stitching. Built for durability and style.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 6,
    "name": "Sweater",
    "brand": "Uniqlo",
    "images": images.productImage6,
    "ratings": 3,
    "rating_count": 25,
    "originalPrice": 29.99,
    "discount": 10,
    "isProductOnSale": false,
    "saleProductPrice": null,
    "isProductNew": false,
    "isProductSold": false,
    "productColor": "Gray",
    "mainProductImageOne": "images.imgMainProductImageOne6",
    "mainProductImageTwo": "images.imgMainProductImageTwo6",
    "description": "Comfortable and warm sweater made from soft knit fabric. Ideal for layering during colder months.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 7,
    "name": "Sneakers",
    "brand": "Nike",
    "images": images.productImage7,
    "ratings": 5,
    "rating_count": 30,
    "originalPrice": 89.99,
    "discount": 25,
    "isProductOnSale": true,
    "saleProductPrice": 67.49,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "White",
    "mainProductImageOne": "images.imgMainProductImageOne7",
    "mainProductImageTwo": "images.imgMainProductImageTwo7",
    "description": "Comfortable sneakers with cushioned sole and breathable mesh upper. Perfect for both athletic and casual wear.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 8,
    "name": "Blazer",
    "brand": "Mango",
    "images": images.productImage8,
    "ratings": 4,
    "rating_count": 12,
    "originalPrice": 79.99,
    "discount": 20,
    "isProductOnSale": false,
    "saleProductPrice": null,
    "isProductNew": false,
    "isProductSold": true,
    "productColor": "Navy",
    "mainProductImageOne": "images.imgMainProductImageOne8",
    "mainProductImageTwo": "images.imgMainProductImageTwo8",
    "description": "Elegant blazer with a tailored fit, ideal for both professional and casual settings. Made from high-quality fabric.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 9,
    "name": "Trousers",
    "brand": "H&M",
    "images": images.productImage9,
    "ratings": 3,
    "rating_count": 18,
    "originalPrice": 39.99,
    "discount": 10,
    "isProductOnSale": true,
    "saleProductPrice": 35.99,
    "isProductNew": false,
    "isProductSold": false,
    "productColor": "Gray",
    "mainProductImageOne": "images.imgMainProductImageOne9",
    "mainProductImageTwo": "images.imgMainProductImageTwo9",
    "description": "Comfortable trousers with a relaxed fit and adjustable waistband. Made from durable fabric suitable for everyday wear.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 10,
    "name": "Cardigan",
    "brand": "Gap",
    "images": images.productImage10,
    "ratings": 4,
    "rating_count": 22,
    "originalPrice": 34.99,
    "discount": 15,
    "isProductOnSale": false,
    "saleProductPrice": null,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "Beige",
    "mainProductImageOne": "images.imgMainProductImageOne10",
    "mainProductImageTwo": "images.imgMainProductImageTwo10",
    "description": "Soft and cozy cardigan with button-front closure and ribbed hem. Perfect for layering during cooler weather.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 11,
    "name": "Polo Shirt",
    "brand": "Ralph Lauren",
    "images": images.productImage11,
    "ratings": 5,
    "rating_count": 14,
    "originalPrice": 49.99,
    "discount": 10,
    "isProductOnSale": true,
    "saleProductPrice": 44.99,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "Red",
    "mainProductImageOne": "images.imgMainProductImageOne11",
    "mainProductImageTwo": "images.imgMainProductImageTwo11",
    "description": "Classic polo shirt with a comfortable fit and embroidered logo. Made from soft cotton fabric.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 12,
    "name": "Running Shorts",
    "brand": "Adidas",
    "images": images.productImage12,
    "ratings": 4,
    "rating_count": 10,
    "originalPrice": 29.99,
    "discount": 20,
    "isProductOnSale": false,
    "saleProductPrice": null,
    "isProductNew": false,
    "isProductSold": true,
    "productColor": "Black",
    "mainProductImageOne": "images.imgMainProductImageOne12",
    "mainProductImageTwo": "images.imgMainProductImageTwo12",
    "description": "Lightweight running shorts with moisture-wicking fabric and an adjustable waistband for a secure fit.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 13,
    "name": "Trench Coat",
    "brand": "Burberry",
    "images": images.productImage13,
    "ratings": 5,
    "rating_count": 8,
    "originalPrice": 299.99,
    "discount": 25,
    "isProductOnSale": true,
    "saleProductPrice": 224.99,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "Beige",
    "mainProductImageOne": "images.imgMainProductImageOne13",
    "mainProductImageTwo": "images.imgMainProductImageTwo13",
    "description": "Classic trench coat with double-breasted front and belted waist. Made from high-quality, weather-resistant fabric.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 14,
    "name": "Belt",
    "brand": "Michael Kors",
    "images": images.productImage14,
    "ratings": 3,
    "rating_count": 6,
    "originalPrice": 69.99,
    "discount": 10,
    "isProductOnSale": false,
    "saleProductPrice": null,
    "isProductNew": false,
    "isProductSold": true,
    "productColor": "Brown",
    "mainProductImageOne": "images.imgMainProductImageOne14",
    "mainProductImageTwo": "images.imgMainProductImageTwo14",
    "description": "Elegant leather belt with a polished buckle. Versatile accessory for both casual and formal outfits.",
    "stocks": 20,
    "isFavorite": false
  },
  {
    "id": 15,
    "name": "Baseball Cap",
    "brand": "New Era",
    "images": images.productImage15,
    "ratings": 4,
    "rating_count": 18,
    "originalPrice": 24.99,
    "discount": 5,
    "isProductOnSale": true,
    "saleProductPrice": 19.99,
    "isProductNew": true,
    "isProductSold": false,
    "productColor": "Navy",
    "mainProductImageOne": "images.imgMainProductImageOne15",
    "mainProductImageTwo": "images.imgMainProductImageTwo15",
    "description": "Stylish baseball cap with adjustable strap and embroidered logo. Perfect for casual wear and outdoor activities.",
    "stocks": 20,
    "isFavorite": false
  }
]

export const reviewsList = [
  {
    customerImg: images.imgAvatar,
    customerName: 'Helene Moore',
    customerRatings: 4,
    reviewPostedDate: 'June 5, 2019',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Aida Bugg',
    customerRatings: 3,
    reviewPostedDate: 'July 2, 2018',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Augusta Wind',
    customerRatings: 4,
    reviewPostedDate: 'April 24, 2019',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Bea Mine',
    customerRatings: 1,
    reviewPostedDate: 'Sept 5, 2022',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'John Dory',
    customerRatings: 5,
    reviewPostedDate: 'Jan 5, 2019',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Mark Ateer',
    customerRatings: 4,
    reviewPostedDate: 'May 5, 2021',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,
  },

]

export const addressList = [
  {
    "id": 1,
    "name": "Jane Doe",
    "address": "3, Newbridge Court",
    "city": "Chino Hills",
    "province": "CA",
    "country": "United States",
    "zipCode": "91709",
    "isDefault": true
  },
  {
    "id": 2,
    "name": "Jane Doe",
    "address": "3, Newbridge Court",
    "city": "Chino Hills",
    "province": "CA",
    "country": "United States",
    "zipCode": "91709",
    "isDefault": false
  },
  {
    "id": 3,
    "name": "Jane Doe",
    "address": "3, Newbridge Court",
    "city": "Chino Hills",
    "province": "CA",
    "country": "United States",
    "zipCode": "91709",
    "isDefault": false
  }
]

export const orderedProducts = [
  {
    id: 1,
    productName: 'Pullover',
    productBrand: 'Mango',
    productColorSelected: 'Black',
    productSizeSelected: 'L',
    productPrice: 51,
    productImage: images.productImage15,
    productQuantity: 1
  },
  {
    id: 2,
    productName: 'T-Shirt',
    productBrand: 'Mango',
    productColorSelected: 'Gray',
    productSizeSelected: 'L',
    productPrice: 22,
    productImage: images.productImage15,
    productQuantity: 1
  },
  {
    id: 3,
    productName: 'Sport Dress',
    productBrand: 'Mango',
    productColorSelected: 'Black',
    productSizeSelected: 'M',
    productPrice: 30,
    productImage: images.productImage15,
    productQuantity: 1
  }
]

export const promoCards = [
  {
    id: 1,
    title: 'Personal Offer',
    code: 'mypromocode2020',
    offerValidity: '6 days remaining',
    promoCodeImage: images.imgDiscount1,
    discount: 10
  },
  {
    id: 2,
    title: 'Summer Sale',
    code: 'summer2020',
    offerValidity: '23 days remaining',
    promoCodeImage: images.imgDiscount2,
    discount: 15
  },
  {
    id: 3,
    title: 'Personal Offer',
    code: 'mypromocode2021',
    offerValidity: '6 days remaining',
    promoCodeImage: images.imgDiscount3,
    discount: 22
  },
]

export const paymentCardDetails = [
  {
    id: 1,
    cardNumber: '1234123412343947',
    cardHolderName: 'John Doe',
    cardExpiryDate: '12/2020',
    cardCvv: '123'
  },
  {
    id: 2,
    cardNumber: '1234123412341234',
    cardHolderName: 'John Doe',
    cardExpiryDate: '12/2020',
    cardCvv: '123'
  }
]

export const userOrdersDetails = [
  {
    orderNo: 1947031,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isCancelled: false,
    isProcessing: false,
    isDelivered: true
  },
  {
    orderNo: 1947032,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isCancelled: false,
    isProcessing: false,
    isDelivered: true
  },
  {
    orderNo: 1947033,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isCancelled: false,
    isProcessing: false,
    isDelivered: true
  },
  {
    orderNo: 1947034,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isCancelled: false,
    isProcessing: false,
    isDelivered: true
  },
  {
    orderNo: 1947035,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isCancelled: false,
    isProcessing: false,
    isDelivered: true
  },
  {
    orderNo: 1947036,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: true,
    isCancelled: false,
    isDelivered: false
  },
  {
    orderNo: 1947037,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: true,
    isCancelled: false,
    isDelivered: false
  },
  {
    orderNo: 1947038,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: true,
    isCancelled: false,
    isDelivered: false
  },
  {
    orderNo: 1947039,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: true,
    isCancelled: false,
    isDelivered: false
  },
  {
    orderNo: 1947040,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: true,
    isCancelled: false,
    isDelivered: false
  },
  {
    orderNo: 1947041,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: false,
    isDelivered: false,
    isCancelled: true,
  },
  {
    orderNo: 1947042,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: false,
    isDelivered: false,
    isCancelled: true,
  },
  {
    orderNo: 1947043,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: false,
    isDelivered: false,
    isCancelled: true,
  },
  {
    orderNo: 1947044,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: false,
    isDelivered: false,
    isCancelled: true,
  },
  {
    orderNo: 1947045,
    orderDate: '05-12-2019',
    trackingNum: 'IW3475453455',
    quantity: 3,
    totalAmount: 112,
    isProcessing: false,
    isDelivered: false,
    isCancelled: true,
  },
]

export const locationData = [
  {
    "id": 1,
    "city": "San Francisco",
    "longitude": -122.4194,
    "latitude": 37.7749
  },
  {
    "id": 2,
    "city": "Sacramento",
    "longitude": -121.4944,
    "latitude": 38.5816
  },
  {
    "id": 3,
    "city": "San Jose",
    "longitude": -121.8863,
    "latitude": 37.3382
  },
  {
    "id": 4,
    "city": "Fresno",
    "longitude": -119.7871,
    "latitude": 36.7378
  },
  {
    "id": 5,
    "city": "Oakland",
    "longitude": -122.2711,
    "latitude": 37.8044
  },
  {
    "id": 6,
    "city": "Stockton",
    "longitude": -121.2908,
    "latitude": 37.9577
  },
  {
    "id": 7,
    "city": "Modesto",
    "longitude": -120.9969,
    "latitude": 37.6391
  },
  {
    "id": 8,
    "city": "Santa Rosa",
    "longitude": -122.7141,
    "latitude": 38.4404
  },
  {
    "id": 9,
    "city": "Napa",
    "longitude": -122.2869,
    "latitude": 38.2975
  },
  {
    "id": 10,
    "city": "Salinas",
    "longitude": -121.6555,
    "latitude": 36.6777
  }
]