import { images } from "../../theme";

export const productList = [
  {
    id: 1,
    name: "Evening Dress",
    brand: "H&M",
    images: images.ImgCard,
    ratings: 3,
    rating_scale: 10.0,
    rating_count: 12,
    originalPrice: 17.99,
    isProductNew: true,
    mainProductImageOne: images.imgMainProductImageOne,
    mainProductImageTwo: images.imgMainProductImageTwo,
    description: 'Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.'
  },
  {
    id: 2,
    name: "Dorothi Perkins",
    merchant: "Sports Dress",
    brand: "Shoemaster",
    images: images.ImgCard,
    ratings: 4,
    rating_scale: 10.0,
    rating_count: 4,
    originalPrice: 22,
    sellingPrice: 11,
    isProductNew: false,
    mainProductImageOne: images.imgMainProductImageOne,
    mainProductImageTwo: images.imgMainProductImageTwo,
    description: 'Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.'
  },
  {
    id: 3,
    name: "Sport Dress",
    merchant: "Example Store",
    brand: "Sitlly",
    images: images.ImgCard,
    ratings: 1,
    rating_scale: 10.0,
    rating_count: 22,
    originalPrice: 14,
    isProductNew: false,
    mainProductImageOne: images.imgMainProductImageOne,
    mainProductImageTwo: images.imgMainProductImageTwo,
    description: 'Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.'
  },
  {
    id: 4,
    name: "Dinner Dress",
    merchant: "Example Store",
    brand: "Puma",
    images: images.ImgCard,
    ratings: 2,
    rating_scale: 10.0,
    rating_count: 12,
    originalPrice: 17,
    isProductNew: true,
    mainProductImageOne: images.imgMainProductImageOne,
    mainProductImageTwo: images.imgMainProductImageTwo,
    description: 'Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.'
  },
  {
    id: 5,
    name: "Shorts",
    merchant: "Example Store",
    brand: "H&M",
    images: images.ImgCard,
    ratings: 4,
    rating_scale: 10.0,
    rating_count: 12,
    isProductNew: true,
    originalPrice: 30,
    sellingPrice: 20.76,
    isProductNew: false,
    mainProductImageOne: images.imgMainProductImageOne,
    mainProductImageTwo: images.imgMainProductImageTwo,
    description: 'Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.'
  },
]

export const reviewsList =[
  {
    customerImg: images.imgAvatar,
    customerName: 'Helene Moore',
    customerRatings: 4,
    reviewPostedDate: 'June 5, 2019',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Aida Bugg',
    customerRatings: 3,
    reviewPostedDate: 'July 2, 2018',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,  
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Augusta Wind',
    customerRatings: 4,
    reviewPostedDate: 'April 24, 2019',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,  
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Bea Mine',
    customerRatings: 1,
    reviewPostedDate: 'Sept 5, 2022',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,  
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'John Dory',
    customerRatings: 5,
    reviewPostedDate: 'Jan 5, 2019',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,  
  },
  {
    customerImg: images.imgAvatar,
    customerName: 'Mark Ateer',
    customerRatings: 4,
    reviewPostedDate: 'May 5, 2021',
    reviewDescription: `The dress is great! Very classy and comfortable. It fit perfectly! I'm 5'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn't recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.`,
    reviewProductImageOne: images.imgReviewProductImgOne,
    reviewProductImageTwo: images.imgReviewProductImgTwo,
    reviewProductImageThree: images.imgReviewProductImgThree,  
  },

]