// INFO: all redux action types


//AUTH
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

//PRODUCTS
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'

//CART
export const ADD_TO_CART = 'ADD_TO_CART'